manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: inorichi
      url-base: https://github.com/inorichi
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
  self:
    path: config

  # manifest:
  # remotes:
  #   - name: zmkfirmware
  #     url-base: https://github.com/petejohanson
  #   - name: m-thw
  #     url-base: https://github.com/m-thw
  # projects:
  #   - name: zmk
  #     remote: zmkfirmware
  #     revision: feat/pointers-move-scroll
  #     import: app/west.yml
  #   - name: zmk-pmw3610-driver
  #     remote: m-thw 
  #     revision: main 
  # self:
  #   path: config